## Section 1: Create and write to a text file
We will create a text file and write some lines into it.

In [ ]:
import os
import csv
import numpy as np

text_path = "arden_notes.txt"

with open(text_path, "w", encoding="utf-8") as f:
    f.write("Hello Arden University!\n")
    f.write("File handling in Python is simple.\n")
    f.write("strip and split help clean and parse lines.\n")

print("File created:", os.path.exists(text_path))

File created: True


## Section 2: Read the full file
Now we will read the complete content of the file.

In [ ]:
with open(text_path, "r", encoding="utf-8") as f:
    content = f.read()

print(content)

Hello Arden University!
File handling in Python is simple.
strip and split help clean and parse lines.
Appending a final line for the demo.



## Section 3: Read part of the file
Now we will read only a few characters from the file.

In [ ]:
with open(text_path, "r", encoding="utf-8") as f:
    first_10 = f.read(10)
    next_8 = f.read(8)

print(first_10)
print(next_8)

Hello Arde
n Univer


## Section 4: Read line by line
Now we will read each line and split it into words.

In [ ]:
with open(text_path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, start=1):
        words = line.strip().split()
        print(f"Line {i}:", words)

Line 1: ['Hello', 'Arden', 'University!']
Line 2: ['File', 'handling', 'in', 'Python', 'is', 'simple.']
Line 3: ['strip', 'and', 'split', 'help', 'clean', 'and', 'parse', 'lines.']
Line 4: ['Appending', 'a', 'final', 'line', 'for', 'the', 'demo.']


## Section 5: Append new content
Now we will add one more line to the file.

In [ ]:
with open(text_path, "a", encoding="utf-8") as f:
    f.write("Appending a final line for the demo.\n")

with open(text_path, "r", encoding="utf-8") as f:
    print(f.read())

Hello Arden University!
File handling in Python is simple.
strip and split help clean and parse lines.
Appending a final line for the demo.



## Section 6: Create a CSV file
Now we will create a simple CSV file with some data.

In [ ]:
csv_path = "employees.csv"

rows = [
    ["name", "employee_no", "school"],
    ["Angela Armstrong", "006001", "Chemical"],
    ["Stuart Smith", "006002", "Structural"]
]

with open(csv_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerows(rows)

print("CSV created:", os.path.exists(csv_path))

CSV created: True


## Section 7: Read the CSV file
Now we will read and display the CSV data.

In [ ]:
with open(csv_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f)
    for i, row in enumerate(reader):
        if i == 0:
            print("Columns:", row)
        else:
            print(row)

Columns: ['name', 'employee_no', 'school']
['Angela Armstrong', '006001', 'Chemical']
['Stuart Smith', '006002', 'Structural']


## Section 8: Create NumPy arrays
Now we will create arrays and check their properties.

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 2, 5]])
arr2 = np.array([1, 3, 2])

print(arr1)
print(arr1.ndim, arr1.shape, arr1.size, arr1.dtype)
print(arr2)

[[1 2 3]
 [4 2 5]]
2 (2, 3) 6 int64
[1 3 2]


## Section 9: Create special arrays
Now we will create arrays filled with zeros, ones, and a fixed value.

In [ ]:
zeros_array = np.zeros((3, 4))
ones_array = np.ones((2, 3))
full_array = np.full((3, 3), 6)

print(zeros_array)
print(ones_array)
print(full_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


## Section 10: Generate values
Now we will generate values using arange and linspace.

In [ ]:
print(np.arange(0, 31, 5))
print(np.linspace(0, 5, 10))

[ 0  5 10 15 20 25 30]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


## Section 11: Reshape array
Now we will change the shape of an array.

In [ ]:
arr3 = np.array([
    [1, 2, 3, 4],
    [5, 2, 4, 2],
    [1, 2, 0, 1]
])

reshaped = arr3.reshape(2, 2, 3)

print(arr3)
print(reshaped)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


## Section 12: Flatten array
Now we will convert a 2D array into 1D.

In [ ]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr4.flatten())

[1 2 3 4 5 6]


## Section 13: Indexing and slicing
Now we will select specific parts of an array.

In [ ]:
a = np.array([
    [-1, 2, 0, 4],
    [4, -0.5, 6, 0],
    [2.6, 0, 7, 8],
    [3, -7, 4, 2.0]
])

print(a[:2, ::3])

[[-1.  4.]
 [ 4.  0.]]


## Section 14: Integer indexing
Now we will pick specific values using positions.

In [ ]:
print(a[[1, 1, 0, 3], [3, 2, 1, 0]])

[0. 6. 2. 3.]


## Section 15: Boolean masking
Now we will filter data using conditions.

In [ ]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([
    [4, 7],
    [0, 2],
    [-5, 6],
    [0, 0],
    [1, 2],
    [-12, -4],
    [3, 4]
])

mask = names == "Bob"

print(data[mask])
print(data[~mask])

[[4 7]
 [0 0]]
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]


## Section 16: Arithmetic operations
Now we will perform basic math operations.

In [ ]:
x = np.array([3, 4, 5])
y = np.array([10, 11, 12])

print(x + y)
print(x * y)

[13 15 17]
[30 44 60]


## Section 17: Broadcasting
Now we will add a row to a matrix.

In [ ]:
M = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])

print(M + row)

[[11 22 33]
 [14 25 36]]


## Section 18: Log functions
Now we will calculate log values.

In [ ]:
arr5 = np.arange(2, 10)

print(np.log(arr5))

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
 2.07944154 2.19722458]


## Section 19: Aggregations
Now we will find max, min, and sum.

In [ ]:
u = np.array([
    [1, 5, 6],
    [4, 7, 2],
    [3, 1, 9]
])

print(u.max())
print(u.min())
print(u.sum())

9
1
38


## Section 20: Matrix operations
Now we will compare elementwise and matrix multiplication.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 3], [2, 1]])

print(A * B)
print(A.dot(B))

[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]


## Section 21: Sorting
Now we will sort lists and arrays.

In [ ]:
numbers = [7, 1, 5, 3]
numbers.sort()
print(numbers)

b = np.array([[1, 4, 2], [3, 0, 5]])
print(np.sort(b))

[1, 3, 5, 7]
[[1 2 4]
 [0 3 5]]


In [ ]:
arr10 = np.array([50,60,120,20,155])

In [ ]:
arr10_celsius_increased = arr10 + 1.5
print(arr10_celsius_increased)

[ 51.5  61.5 121.5  21.5 156.5]


In [ ]:
arr10_fahrenheit = (arr10_celsius_increased * 9/5) + 32
print(arr10_fahrenheit)

[124.7 142.7 250.7  70.7 313.7]


In [ ]:
arr10_fahrenheit[arr10_fahrenheit > 100] = 100
print(arr10_fahrenheit)

[100.  100.  100.   70.7 100. ]
