In [21]:
import pandas as pd
import numpy as np

In [22]:
product_prices = np.array([[100, 200, 150, 300],
[120, 180, 160, 280],
[90, 220, 140, 310],
[110, 210, 170, 290]])

tax_prices = np.array([0.05, 0.10, 0.08, 0.12])
print(tax_prices)

[0.05 0.1  0.08 0.12]


In [27]:
applied_rates =  product_prices * (1 + tax_prices)
print(applied_rates)

[[105.  220.  162.  336. ]
 [126.  198.  172.8 313.6]
 [ 94.5 242.  151.2 347.2]
 [115.5 231.  183.6 324.8]]


In [29]:
new_rates = np.sum(applied_rates,axis=0)

In [32]:
highest_total = np.argmax(new_rates)

In [33]:
print (highest_total)

3
